export const PRESETS = {
  subtleRoom: {
    distance: 0.2,
    wall: 0.2,
    material: "drywall",
    sourceRoom: 0.25,
    listenerRoom: 0.35,
    leak: 0.12,
    roomMix: 0.14,
    predelayMs: 10,
    outGain: 1,
  },
  nextRoom: {
    distance: 0.45,
    wall: 0.55,
    material: "drywall",
    sourceRoom: 0.35,
    listenerRoom: 0.55,
    leak: 0.08,
    roomMix: 0.22,
    predelayMs: 12,
    outGain: 1,
  },
  behindDoor: {
    distance: 0.4,
    wall: 0.6,
    material: "door",
    sourceRoom: 0.35,
    listenerRoom: 0.45,
    leak: 0.12,
    roomMix: 0.18,
    predelayMs: 9,
    outGain: 1,
  },
  brickMuffle: {
    distance: 0.55,
    wall: 0.75,
    material: "brick",
    sourceRoom: 0.35,
    listenerRoom: 0.5,
    leak: 0.05,
    roomMix: 0.26,
    predelayMs: 14,
    outGain: 1.02,
  },
  curtainLeak: {
    distance: 0.35,
    wall: 0.25,
    material: "curtain",
    sourceRoom: 0.3,
    listenerRoom: 0.55,
    leak: 0.22,
    roomMix: 0.24,
    predelayMs: 16,
    outGain: 1,
  },
};

