#include "PluginProcessor.h"
#include "PluginEditor.h"
#include <algorithm>
#include <cmath>
#include <limits>

namespace { float c01(float v) { return juce::jlimit(0.0f, 1.0f, v); } }

CartridgeEngineAudioProcessor::CartridgeEngineAudioProcessor()
    : AudioProcessor(BusesProperties().withInput("Input",juce::AudioChannelSet::stereo(),true).withOutput("Output",juce::AudioChannelSet::stereo(),true)),
      apvts(*this,nullptr,"PARAMS",createParameterLayout())
{
    apvts.state.setProperty("engineId","cartridge",nullptr); apvts.state.setProperty("schemaVersion",4,nullptr);
}

juce::AudioProcessorValueTreeState::ParameterLayout CartridgeEngineAudioProcessor::createParameterLayout()
{
    std::vector<std::unique_ptr<juce::RangedAudioParameter>>p; const auto n=juce::NormalisableRange<float>(0,1,.001f);
    // V1/V2/V3 order is immutable for existing projects and automation.
    p.push_back(std::make_unique<juce::AudioParameterFloat>("quality","Quality",n,.55f));p.push_back(std::make_unique<juce::AudioParameterFloat>("codec","Codec",n,.25f));p.push_back(std::make_unique<juce::AudioParameterFloat>("grit","Grit",n,.25f));p.push_back(std::make_unique<juce::AudioParameterFloat>("noise","Noise",n,.025f));
    p.push_back(std::make_unique<juce::AudioParameterBool>("dither","Dither",false));p.push_back(std::make_unique<juce::AudioParameterBool>("noiseShaping","Noise Shaping",false));p.push_back(std::make_unique<juce::AudioParameterInt>("bits","Bits",2,16,9));p.push_back(std::make_unique<juce::AudioParameterFloat>("rate","Rate",juce::NormalisableRange<float>(6000.0f,48000.0f,1.0f),22033.0f));p.push_back(std::make_unique<juce::AudioParameterFloat>("jitter","Jitter",n,.135f));
    p.push_back(std::make_unique<juce::AudioParameterFloat>("lpHz","LP",juce::NormalisableRange<float>(2500.0f,18000.0f,1.0f),5440.0f));p.push_back(std::make_unique<juce::AudioParameterFloat>("hpHz","HP",juce::NormalisableRange<float>(20.0f,420.0f,1.0f),126.0f));p.push_back(std::make_unique<juce::AudioParameterFloat>("preEmph","Pre Emphasis",n,.159f));p.push_back(std::make_unique<juce::AudioParameterFloat>("mulaw","Companding",n,.136f));p.push_back(std::make_unique<juce::AudioParameterFloat>("blockMs","Block",juce::NormalisableRange<float>(0.0f,60.0f,.1f),6.0f));
    p.push_back(std::make_unique<juce::AudioParameterFloat>("sat","Saturation",n,.163f));p.push_back(std::make_unique<juce::AudioParameterFloat>("edge","DAC Edge",n,.167f));p.push_back(std::make_unique<juce::AudioParameterFloat>("noiseTrack","Noise Tracking",n,.463f));p.push_back(std::make_unique<juce::AudioParameterFloat>("dcDrift","DC Drift",n,.025f));p.push_back(std::make_unique<juce::AudioParameterFloat>("speaker","Speaker",n,.608f));p.push_back(std::make_unique<juce::AudioParameterFloat>("hum","Hum",n,.008f));p.push_back(std::make_unique<juce::AudioParameterFloat>("whine","Whine",n,.008f));
    p.push_back(std::make_unique<juce::AudioParameterFloat>("bleepsMix","Chip Voice Mix",n,.12f));p.push_back(std::make_unique<juce::AudioParameterFloat>("bleepsRate","Chip Voice Rate",juce::NormalisableRange<float>(0.0f,18.0f,.01f),3.0f));p.push_back(std::make_unique<juce::AudioParameterChoice>("bleepsWave","Chip Wave",juce::StringArray{"Alternate","Pulse","Saw","Triangle","Noise"},0));p.push_back(std::make_unique<juce::AudioParameterFloat>("bleepsVibrato","Chip Vibrato",n,.12f));p.push_back(std::make_unique<juce::AudioParameterFloat>("bleepsPitch","Chip Pitch",n,.55f));p.push_back(std::make_unique<juce::AudioParameterBool>("bleepsEnable","Chip Voice",false));
    p.push_back(std::make_unique<juce::AudioParameterFloat>("microDelayMs","Micro Delay",juce::NormalisableRange<float>(0.0f,30.0f,.1f),3.0f));p.push_back(std::make_unique<juce::AudioParameterFloat>("microDelayMix","Micro Delay Mix",n,.061f));p.push_back(std::make_unique<juce::AudioParameterFloat>("verb","Room",n,.039f));p.push_back(std::make_unique<juce::AudioParameterFloat>("verbMs","Room Time",juce::NormalisableRange<float>(10.0f,120.0f,.1f),30.0f));p.push_back(std::make_unique<juce::AudioParameterFloat>("wet","Mix",n,1.0f));p.push_back(std::make_unique<juce::AudioParameterFloat>("ceiling","Ceiling",juce::NormalisableRange<float>(.2f,1.0f,.001f),.936f));p.push_back(std::make_unique<juce::AudioParameterFloat>("limiter","Limiter",n,.260f));p.push_back(std::make_unique<juce::AudioParameterFloat>("outGain","Output",juce::NormalisableRange<float>(0.0f,1.5f,.01f),.95f));
    p.push_back(std::make_unique<juce::AudioParameterBool>("macroLink","Legacy Macro Link",false));p.push_back(std::make_unique<juce::AudioParameterChoice>("codecMode","Codec Memory",juce::StringArray{"PCM","DPCM","ADPCM","BRR","MU-Law"},2));p.push_back(std::make_unique<juce::AudioParameterChoice>("speakerModel","Playback Hardware",juce::StringArray{"Direct","Handheld","Television","Cabinet","PC Speaker"},1));p.push_back(std::make_unique<juce::AudioParameterChoice>("bleepsTrigger","Chip Trigger",juce::StringArray{"Transients","Clock","Hybrid"},0));p.push_back(std::make_unique<juce::AudioParameterChoice>("bleepsScale","Chip Scale",juce::StringArray{"Pentatonic","Minor","Major","Chromatic"},1));p.push_back(std::make_unique<juce::AudioParameterFloat>("inputGain","Input Gain",juce::NormalisableRange<float>(-24.0f,24.0f,.1f),0.0f));
    const juce::StringArray divisions{"1 Bar","1/2","1/4","1/8","1/16","1/32","1/4T","1/8T","1/16T","1/8D","1/16D"};
    p.push_back(std::make_unique<juce::AudioParameterBool>("tempoSync","Chip Tempo Sync",false));p.push_back(std::make_unique<juce::AudioParameterChoice>("syncDivision","Chip Division",divisions,4));
    // V4: actual cartridge-bus failures and deterministic performer clocks.
    p.push_back(std::make_unique<juce::AudioParameterFloat>("addressWear","Address Wear",n,0.0f));p.push_back(std::make_unique<juce::AudioParameterFloat>("busDepth","Bus Corruption Depth",n,.35f));
    p.push_back(std::make_unique<juce::AudioParameterBool>("stallSync","Clock ROM Stalls",false));p.push_back(std::make_unique<juce::AudioParameterChoice>("stallDivision","ROM Stall Grid",divisions,3));p.push_back(std::make_unique<juce::AudioParameterFloat>("stallProbability","ROM Stall Probability",n,.35f));p.push_back(std::make_unique<juce::AudioParameterFloat>("stallStrength","ROM Stall Strength",n,.8f));p.push_back(std::make_unique<juce::AudioParameterFloat>("stallDurationMs","ROM Stall Length",juce::NormalisableRange<float>(8.0f,1200.0f,1.0f),180.0f));p.push_back(std::make_unique<juce::AudioParameterBool>("stallLengthSync","Clock Stall Length",false));p.push_back(std::make_unique<juce::AudioParameterChoice>("stallLengthDivision","ROM Stall Length Grid",divisions,4));p.push_back(std::make_unique<juce::AudioParameterFloat>("stallRepeatMs","ROM Repeat Window",juce::NormalisableRange<float>(2.0f,300.0f,1.0f),42.0f));p.push_back(std::make_unique<juce::AudioParameterBool>("stallRepeatSync","Clock Repeat Window",false));p.push_back(std::make_unique<juce::AudioParameterChoice>("stallRepeatDivision","ROM Repeat Grid",divisions,5));
    p.push_back(std::make_unique<juce::AudioParameterBool>("bankSync","Clock Bank Faults",false));p.push_back(std::make_unique<juce::AudioParameterChoice>("bankDivision","Bank Fault Grid",divisions,2));p.push_back(std::make_unique<juce::AudioParameterFloat>("bankProbability","Bank Fault Probability",n,.28f));p.push_back(std::make_unique<juce::AudioParameterFloat>("bankStrength","Bank Fault Strength",n,.62f));p.push_back(std::make_unique<juce::AudioParameterFloat>("bankDurationMs","Bank Fault Length",juce::NormalisableRange<float>(4.0f,800.0f,1.0f),74.0f));p.push_back(std::make_unique<juce::AudioParameterBool>("bankLengthSync","Clock Bank Length",false));p.push_back(std::make_unique<juce::AudioParameterChoice>("bankLengthDivision","Bank Fault Length Grid",divisions,5));p.push_back(std::make_unique<juce::AudioParameterFloat>("chipProbability","Chip Voice Probability",n,.65f));
    return{p.begin(),p.end()};
}

float CartridgeEngineAudioProcessor::value(const char*id)const noexcept{if(const auto*v=apvts.getRawParameterValue(id))return v->load(std::memory_order_relaxed);return 0;}
bool CartridgeEngineAudioProcessor::legacyMacrosActive()const noexcept{return value("macroLink")>.5f;}
void CartridgeEngineAudioProcessor::materialiseLegacyMacros()
{
    if(!legacyMacrosActive())return;const auto codec=(lost_audio::core::CartridgeCodec)juce::jlimit(0,4,(int)std::lround(value("codecMode")));const auto speaker=(lost_audio::core::CartridgeSpeaker)juce::jlimit(0,4,(int)std::lround(value("speakerModel")));const auto t=lost_audio::core::mapCartridgeMacros(codec,speaker,value("quality"),value("codec"),value("grit"),value("noise"));
    const auto set=[this](const char*id,float plain){if(auto*p=apvts.getParameter(id))p->setValueNotifyingHost(p->convertTo0to1(plain));};set("bits",(float)t.bits);set("rate",t.converterRateHz);set("jitter",t.jitter);set("lpHz",t.lowPassHz);set("hpHz",t.highPassHz);set("preEmph",t.preEmphasis);set("mulaw",t.companding);set("blockMs",t.blockMs);set("sat",t.saturation);set("edge",t.edge);set("dcDrift",t.dcDrift);set("hum",t.hum);set("whine",t.whine);set("noise",t.noise);set("noiseTrack",t.noiseTracking);set("speaker",t.speaker);set("microDelayMs",t.microDelayMs);set("microDelayMix",t.microDelayMix);set("verb",t.room);set("verbMs",t.roomMs);set("limiter",t.limiter);set("ceiling",t.ceiling);set("outGain",t.outputGain);set("macroLink",0);
}
std::array<float,64> CartridgeEngineAudioProcessor::outputTrace()const noexcept{std::array<float,64>r{};for(std::size_t i=0;i<r.size();++i)r[i]=trace[i].load(std::memory_order_relaxed);return r;}
float CartridgeEngineAudioProcessor::syncedMilliseconds(const char*sync,const char*division,double bpm)const noexcept{return value(sync)>.5f?lost_audio::core::tempoDivisionMilliseconds(bpm,(int)value(division)):0.0f;}

const juce::String CartridgeEngineAudioProcessor::getName()const{return JucePlugin_Name;}bool CartridgeEngineAudioProcessor::acceptsMidi()const{return false;}bool CartridgeEngineAudioProcessor::producesMidi()const{return false;}bool CartridgeEngineAudioProcessor::isMidiEffect()const{return false;}double CartridgeEngineAudioProcessor::getTailLengthSeconds()const{return .2;}int CartridgeEngineAudioProcessor::getNumPrograms(){return 1;}int CartridgeEngineAudioProcessor::getCurrentProgram(){return 0;}void CartridgeEngineAudioProcessor::setCurrentProgram(int){}const juce::String CartridgeEngineAudioProcessor::getProgramName(int){return{};}void CartridgeEngineAudioProcessor::changeProgramName(int,const juce::String&){}
void CartridgeEngineAudioProcessor::prepareToPlay(double sr,int block){juce::ignoreUnused(block);core.prepare(sr,(std::size_t)juce::jlimit(1,2,getTotalNumInputChannels()));core.reset(0xfeedc0deu);currentBpm=120;setLatencySamples(0);for(auto&x:inputPeaks)x.store(0);for(auto&x:outputPeaks)x.store(0);for(auto&x:trace)x.store(0);pendingStall.store(false);pendingBank.store(false);pendingBleep.store(false);}void CartridgeEngineAudioProcessor::releaseResources(){}bool CartridgeEngineAudioProcessor::isBusesLayoutSupported(const BusesLayout&l)const{const auto in=l.getMainInputChannelSet();return in==l.getMainOutputChannelSet()&&(in==juce::AudioChannelSet::mono()||in==juce::AudioChannelSet::stereo());}

lost_audio::core::CartridgeParameters CartridgeEngineAudioProcessor::readParameters()const noexcept
{
    lost_audio::core::CartridgeParameters p;p.codecMode=(lost_audio::core::CartridgeCodec)juce::jlimit(0,4,(int)std::lround(value("codecMode")));p.speakerModel=(lost_audio::core::CartridgeSpeaker)juce::jlimit(0,4,(int)std::lround(value("speakerModel")));p.bleepsEnabled=value("bleepsEnable")>.5f;p.bleepWave=(lost_audio::core::BleepWave)juce::jlimit(0,4,(int)std::lround(value("bleepsWave")));p.bleepTrigger=(lost_audio::core::BleepTrigger)juce::jlimit(0,2,(int)std::lround(value("bleepsTrigger")));p.bleepScale=(lost_audio::core::BleepScale)juce::jlimit(0,3,(int)std::lround(value("bleepsScale")));p.bleepMix=value("bleepsMix");p.bleepRate=value("bleepsRate");p.bleepVibrato=value("bleepsVibrato");p.bleepPitch=value("bleepsPitch");p.dither=value("dither")>.5f;p.noiseShaping=value("noiseShaping")>.5f;p.inputGain=juce::Decibels::decibelsToGain(value("inputGain"));p.mix=c01(value("wet"));p.addressWear=value("addressWear");p.busDepth=value("busDepth");
    if(legacyMacrosActive()){const auto t=lost_audio::core::mapCartridgeMacros(p.codecMode,p.speakerModel,value("quality"),value("codec"),value("grit"),value("noise"));p.bits=t.bits;p.converterRateHz=t.converterRateHz;p.jitter=t.jitter;p.lowPassHz=t.lowPassHz;p.highPassHz=t.highPassHz;p.preEmphasis=t.preEmphasis;p.companding=t.companding;p.blockMs=t.blockMs;p.saturation=t.saturation;p.edge=t.edge;p.dcDrift=t.dcDrift;p.hum=t.hum;p.whine=t.whine;p.noise=t.noise;p.noiseTracking=t.noiseTracking;p.speaker=t.speaker;p.microDelayMs=t.microDelayMs;p.microDelayMix=t.microDelayMix;p.room=t.room;p.roomMs=t.roomMs;p.limiter=t.limiter;p.ceiling=t.ceiling;p.outputGain=juce::jlimit(0.0f,1.5f,t.outputGain*value("outGain")/.95f);}
    else{p.bits=(int)std::lround(value("bits"));p.converterRateHz=value("rate");p.jitter=value("jitter");p.lowPassHz=value("lpHz");p.highPassHz=value("hpHz");p.preEmphasis=value("preEmph");p.companding=value("mulaw");p.blockMs=value("blockMs");p.saturation=value("sat");p.edge=value("edge");p.dcDrift=value("dcDrift");p.hum=value("hum");p.whine=value("whine");p.noise=value("noise");p.noiseTracking=value("noiseTrack");p.speaker=value("speaker");p.microDelayMs=value("microDelayMs");p.microDelayMix=value("microDelayMix");p.room=value("verb");p.roomMs=value("verbMs");p.limiter=value("limiter");p.ceiling=value("ceiling");p.outputGain=value("outGain");}return p;
}

void CartridgeEngineAudioProcessor::processBlock(juce::AudioBuffer<float>&b,juce::MidiBuffer&m)
{
    juce::ignoreUnused(m);juce::ScopedNoDenormals nd;const auto channels=juce::jlimit(0,2,getTotalNumInputChannels()),samples=b.getNumSamples();for(int ch=channels;ch<getTotalNumOutputChannels();++ch)b.clear(ch,0,samples);if(channels==0||samples<=0||getSampleRate()<=0)return;for(int ch=0;ch<channels;++ch)inputPeaks[(std::size_t)ch].store(b.getMagnitude(ch,0,samples));if(channels==1)inputPeaks[1].store(inputPeaks[0].load());
    bool playing=false,hasPpq=false;double ppq=0;if(auto*head=getPlayHead())if(const auto pos=head->getPosition()){playing=pos->getIsPlaying();if(const auto bpm=pos->getBpm())currentBpm=*bpm;if(const auto hostPpq=pos->getPpqPosition()){ppq=*hostPpq;hasPpq=true;}}
    lost_audio::core::TempoEventSchedule stallSchedule,bankSchedule,chipSchedule;if(playing&&hasPpq&&value("stallSync")>.5f)stallSchedule=lost_audio::core::tempoEventsInBlock(ppq,currentBpm,(int)value("stallDivision"),getSampleRate(),samples);if(playing&&hasPpq&&value("bankSync")>.5f)bankSchedule=lost_audio::core::tempoEventsInBlock(ppq,currentBpm,(int)value("bankDivision"),getSampleRate(),samples);if(playing&&hasPpq&&value("tempoSync")>.5f)chipSchedule=lost_audio::core::tempoEventsInBlock(ppq,currentBpm,(int)value("syncDivision"),getSampleRate(),samples);
    std::vector<int> boundaries{0,samples};for(std::size_t i=0;i<stallSchedule.size;++i)boundaries.push_back(stallSchedule.events[i].sampleOffset);for(std::size_t i=0;i<bankSchedule.size;++i)boundaries.push_back(bankSchedule.events[i].sampleOffset);for(std::size_t i=0;i<chipSchedule.size;++i)boundaries.push_back(chipSchedule.events[i].sampleOffset);std::sort(boundaries.begin(),boundaries.end());boundaries.erase(std::unique(boundaries.begin(),boundaries.end()),boundaries.end());
    auto fireStall=pendingStall.exchange(false),fireBank=pendingBank.exchange(false),fireChip=pendingBleep.exchange(false);auto parameters=readParameters();if(value("tempoSync")>.5f)core.setBleepClockSamples(std::numeric_limits<int>::max()/2);
    const auto stallMs=value("stallLengthSync")>.5f?syncedMilliseconds("stallLengthSync","stallLengthDivision",currentBpm):value("stallDurationMs");const auto repeatMs=value("stallRepeatSync")>.5f?syncedMilliseconds("stallRepeatSync","stallRepeatDivision",currentBpm):value("stallRepeatMs");const auto bankMs=value("bankLengthSync")>.5f?syncedMilliseconds("bankLengthSync","bankLengthDivision",currentBpm):value("bankDurationMs");
    for(std::size_t segment=0;segment+1<boundaries.size();++segment){const auto offset=boundaries[segment],count=boundaries[segment+1]-offset;for(std::size_t i=0;i<stallSchedule.size;++i)if(stallSchedule.events[i].sampleOffset==offset&&lost_audio::core::tempoEventDecision(stallSchedule.events[i].stepIndex,value("stallProbability"),0x43415254u))fireStall=true;for(std::size_t i=0;i<bankSchedule.size;++i)if(bankSchedule.events[i].sampleOffset==offset&&lost_audio::core::tempoEventDecision(bankSchedule.events[i].stepIndex,value("bankProbability"),0x42414e4bu))fireBank=true;for(std::size_t i=0;i<chipSchedule.size;++i)if(chipSchedule.events[i].sampleOffset==offset&&lost_audio::core::tempoEventDecision(chipSchedule.events[i].stepIndex,value("chipProbability"),0x43484950u))fireChip=true;
        if(fireStall&&!core.stallActive()){core.triggerRomStall(value("stallStrength"),(int)std::lround(stallMs*.001*getSampleRate()),(int)std::lround(repeatMs*.001*getSampleRate()));fireStall=false;}if(fireBank&&!core.bankFaultActive()){core.triggerBankFault(value("bankStrength"),(int)std::lround(bankMs*.001*getSampleRate()));fireBank=false;}if(fireChip&&parameters.bleepsEnabled&&!core.bleepActive()){core.triggerBleep();fireChip=false;}float*p[]{b.getWritePointer(0,offset),channels>1?b.getWritePointer(1,offset):nullptr};core.process(p,(std::size_t)channels,(std::size_t)count,parameters);}
    for(int ch=0;ch<channels;++ch)outputPeaks[(std::size_t)ch].store(core.outputPeak((std::size_t)ch));if(channels==1)outputPeaks[1].store(outputPeaks[0].load());for(std::size_t i=0;i<trace.size();++i){const auto at=juce::jlimit(0,samples-1,(int)std::lround((double)i*(samples-1)/(trace.size()-1)));trace[i].store(b.getSample(0,at));}bleepState.store(core.bleepActive());stallState.store(core.stallActive());bankState.store(core.bankFaultActive());stallProgressMeter.store(core.stallProgress());bankProgressMeter.store(core.bankFaultProgress());
}

bool CartridgeEngineAudioProcessor::hasEditor()const{return true;}juce::AudioProcessorEditor*CartridgeEngineAudioProcessor::createEditor(){return new CartridgeEngineAudioProcessorEditor(*this);}void CartridgeEngineAudioProcessor::getStateInformation(juce::MemoryBlock&d){auto s=apvts.copyState();s.setProperty("engineId","cartridge",nullptr);s.setProperty("schemaVersion",4,nullptr);if(auto x=s.createXml())copyXmlToBinary(*x,d);}void CartridgeEngineAudioProcessor::setStateInformation(const void*d,int z){if(auto x=getXmlFromBinary(d,z))if(x->hasTagName(apvts.state.getType()))apvts.replaceState(juce::ValueTree::fromXml(*x));}juce::AudioProcessor*JUCE_CALLTYPE createPluginFilter(){return new CartridgeEngineAudioProcessor();}
