#include "../src/PluginProcessor.h"
#include <cmath>
#include <cstdlib>
#include <iostream>

namespace
{
void set(juce::AudioProcessorValueTreeState&s,const char*id,float v){auto*p=s.getParameter(id);if(!p)std::exit(2);p->setValueNotifyingHost(p->convertTo0to1(v));}
float renderDefaultMaxImpulse()
{
    constexpr int sampleRate=44100,blockSize=512,totalSamples=sampleRate*5,warmup=sampleRate;
    CartridgeEngineAudioProcessor processor;processor.setRateAndBufferSizeDetails(sampleRate,blockSize);processor.prepareToPlay(sampleRate,blockSize);
    juce::AudioBuffer<float> buffer(2,blockSize);juce::MidiBuffer midi;float previous2=0,previous1=0,maxImpulse=0;
    for(int offset=0;offset<totalSamples;offset+=blockSize){const auto count=std::min(blockSize,totalSamples-offset);buffer.setSize(2,count,false,false,true);for(int i=0;i<count;++i){const auto sample=.14f*std::sin(juce::MathConstants<float>::twoPi*997.0f*(float)(offset+i)/(float)sampleRate);buffer.setSample(0,i,sample);buffer.setSample(1,i,sample);}processor.processBlock(buffer,midi);for(int i=0;i<count;++i){const auto current=buffer.getSample(0,i);if(offset+i>=warmup)maxImpulse=std::max(maxImpulse,std::abs(current-2.0f*previous1+previous2));previous2=previous1;previous1=current;}}
    return maxImpulse;
}
float renderPresetTransitionMaxImpulse()
{
    constexpr int sampleRate=44100,blockSize=512,totalSamples=sampleRate*5,warmup=sampleRate;
    CartridgeEngineAudioProcessor processor;processor.setRateAndBufferSizeDetails(sampleRate,blockSize);processor.prepareToPlay(sampleRate,blockSize);auto& state=processor.getAPVTS();
    juce::AudioBuffer<float> buffer(2,blockSize);juce::MidiBuffer midi;float previous2=0,previous1=0,maxImpulse=0;bool changed=false;int maxIndex=-1,changeIndex=-1;
    for(int offset=0;offset<totalSamples;offset+=blockSize){if(!changed&&offset>=sampleRate*2){set(state,"codecMode",1);set(state,"speakerModel",3);set(state,"quality",.28f);set(state,"codec",.32f);set(state,"grit",.62f);set(state,"noise",.06f);set(state,"macroLink",1);processor.materialiseLegacyMacros();changed=true;changeIndex=offset;}const auto count=std::min(blockSize,totalSamples-offset);buffer.setSize(2,count,false,false,true);for(int i=0;i<count;++i){const auto sample=.14f*std::sin(juce::MathConstants<float>::twoPi*997.0f*(float)(offset+i)/(float)sampleRate);buffer.setSample(0,i,sample);buffer.setSample(1,i,sample);}processor.processBlock(buffer,midi);for(int i=0;i<count;++i){const auto current=buffer.getSample(0,i);if(offset+i>=warmup){const auto impulse=std::abs(current-2.0f*previous1+previous2);if(impulse>maxImpulse){maxImpulse=impulse;maxIndex=offset+i;}}previous2=previous1;previous1=current;}}
    std::cout<<"Cartridge transition peak offset: "<<(maxIndex-changeIndex)<<" samples\n";
    return maxImpulse;
}
float renderEditorPresetDifference(int selectedId,juce::String&name,bool&materialised)
{
    constexpr int sampleRate=44100,blockSize=512,totalSamples=sampleRate;
    CartridgeEngineAudioProcessor processor;std::unique_ptr<juce::AudioProcessorEditor> editor(processor.createEditor());juce::ComboBox* selector=nullptr;for(int i=0;i<editor->getNumChildComponents();++i)if(auto*box=dynamic_cast<juce::ComboBox*>(editor->getChildComponent(i));box&&box->getNumItems()>10){selector=box;break;}if(!selector)return -1;selector->setSelectedId(selectedId,juce::sendNotificationSync);name=selector->getText();materialised=!processor.legacyMacrosActive();processor.setRateAndBufferSizeDetails(sampleRate,blockSize);processor.prepareToPlay(sampleRate,blockSize);juce::AudioBuffer<float>audio(2,totalSamples);for(int i=0;i<totalSamples;++i){const auto x=.14f*std::sin(juce::MathConstants<float>::twoPi*997.0f*(float)i/(float)sampleRate);audio.setSample(0,i,x);audio.setSample(1,i,x);}juce::MidiBuffer midi;for(int offset=0;offset<totalSamples;offset+=blockSize){const auto count=std::min(blockSize,totalSamples-offset);juce::AudioBuffer<float>view(audio.getArrayOfWritePointers(),2,offset,count);processor.processBlock(view,midi);}double difference=0;for(int i=sampleRate/4;i<totalSamples;++i){const auto input=.14f*std::sin(juce::MathConstants<float>::twoPi*997.0f*(float)i/(float)sampleRate);difference+=std::abs(audio.getSample(0,i)-input);}return(float)(difference/(totalSamples-sampleRate/4));
}
}
int main()
{
    juce::ScopedJuceInitialiser_GUI gui;CartridgeEngineAudioProcessor p;auto&s=p.getAPVTS();
    if(p.legacyMacrosActive()||!s.getParameter("stallSync")||!s.getParameter("bankSync")||!s.getParameter("chipProbability")){std::cerr<<"Cartridge V4 contract missing\n";return 1;}
    const auto initial=lost_audio::core::mapCartridgeMacros(lost_audio::core::CartridgeCodec::adpcm,lost_audio::core::CartridgeSpeaker::handheld,.55f,.25f,.25f,.10f);
    if(std::abs(s.getRawParameterValue("bits")->load()-initial.bits)>.1f||std::abs(s.getRawParameterValue("rate")->load()-initial.converterRateHz)>1.1f||std::abs(s.getRawParameterValue("speaker")->load()-initial.speaker)>.011f){std::cerr<<"Canonical defaults drifted from legacy cartridge sound\n";return 1;}
    s.state.setProperty("factoryPresetName","Arcade Cabinet",nullptr);juce::MemoryBlock savedState;p.getStateInformation(savedState);CartridgeEngineAudioProcessor restored;restored.setStateInformation(savedState.getData(),(int)savedState.getSize());if(restored.getAPVTS().state.getProperty("factoryPresetName").toString()!="Arcade Cabinet"){std::cerr<<"Cartridge named preset identity did not survive host state restore\n";return 1;}
    CartridgeEngineAudioProcessor uiPreset;std::unique_ptr<juce::AudioProcessorEditor> editor(uiPreset.createEditor());juce::ComboBox* presetSelector=nullptr;for(int i=0;i<editor->getNumChildComponents();++i)if(auto* box=dynamic_cast<juce::ComboBox*>(editor->getChildComponent(i));box&&box->getNumItems()>10){presetSelector=box;break;}if(!presetSelector){std::cerr<<"Cartridge factory preset selector is not reachable through the real editor\n";return 1;}presetSelector->setSelectedId(10,juce::sendNotificationSync);auto&uiState=uiPreset.getAPVTS();if(uiState.state.getProperty("factoryPresetName").toString()!="Arcade Cabinet"||std::lround(uiState.getRawParameterValue("codecMode")->load())!=1||std::lround(uiState.getRawParameterValue("speakerModel")->load())!=3||uiPreset.legacyMacrosActive()){std::cerr<<"Cartridge editor selection did not materialise Arcade Cabinet immediately\n";return 1;}uiPreset.setRateAndBufferSizeDetails(44100,512);uiPreset.prepareToPlay(44100,512);juce::AudioBuffer<float>uiAudio(2,44100);double audibleDifference=0;for(int i=0;i<uiAudio.getNumSamples();++i){const auto x=.14f*std::sin(juce::MathConstants<float>::twoPi*997.0f*(float)i/44100.0f);uiAudio.setSample(0,i,x);uiAudio.setSample(1,i,x);}juce::MidiBuffer uiMidi;for(int offset=0;offset<uiAudio.getNumSamples();offset+=512){const auto count=std::min(512,uiAudio.getNumSamples()-offset);juce::AudioBuffer<float>view(uiAudio.getArrayOfWritePointers(),2,offset,count);uiPreset.processBlock(view,uiMidi);}for(int i=0;i<uiAudio.getNumSamples();++i){const auto input=.14f*std::sin(juce::MathConstants<float>::twoPi*997.0f*(float)i/44100.0f);audibleDifference+=std::abs(uiAudio.getSample(0,i)-input);}audibleDifference/=uiAudio.getNumSamples();if(audibleDifference<.01){std::cerr<<"Cartridge editor-selected Arcade Cabinet rendered effectively clean\n";return 1;}
    set(s,"codecMode",3);set(s,"speakerModel",4);set(s,"quality",.22f);set(s,"codec",.72f);set(s,"grit",.66f);set(s,"noise",.18f);set(s,"macroLink",1);const auto target=lost_audio::core::mapCartridgeMacros(lost_audio::core::CartridgeCodec::brr,lost_audio::core::CartridgeSpeaker::pcSpeaker,.22f,.72f,.66f,.18f);p.materialiseLegacyMacros();if(p.legacyMacrosActive()||std::abs(s.getRawParameterValue("rate")->load()-target.converterRateHz)>1.1f||std::abs(s.getRawParameterValue("edge")->load()-target.edge)>.011f){std::cerr<<"Legacy macro migration failed\n";return 1;}
    p.setRateAndBufferSizeDetails(48000,256);p.prepareToPlay(48000,256);set(s,"addressWear",0);set(s,"bleepsEnable",1);set(s,"stallDurationMs",140);set(s,"stallRepeatMs",24);set(s,"bankDurationMs",110);p.triggerRomStall();p.triggerBankFault();p.triggerChipVoice();juce::AudioBuffer<float>b(2,1024);for(int i=0;i<b.getNumSamples();++i){const auto x=.2f*std::sin((float)i*.071f);b.setSample(0,i,x);b.setSample(1,i,-x*.8f);}juce::MidiBuffer midi;p.processBlock(b,midi);
    if(!p.stallActive()||p.stallProgress()<=0||!p.bankFaultActive()||p.bankFaultProgress()<=0||!p.bleepActive()){std::cerr<<"Conducted cartridge events or telemetry failed\n";return 1;}if(!std::isfinite(b.getMagnitude(0,0,b.getNumSamples()))||b.getMagnitude(0,0,b.getNumSamples())>1.001f){std::cerr<<"Cartridge safety bound failed\n";return 1;}
    CartridgeEngineAudioProcessor quiet;quiet.setRateAndBufferSizeDetails(48000,256);quiet.prepareToPlay(48000,256);juce::AudioBuffer<float> silence(2,48000);silence.clear();juce::MidiBuffer quietMidi;quiet.processBlock(silence,quietMidi);if(silence.getRMSLevel(0,0,silence.getNumSamples())>.0001f){std::cerr<<"Cartridge default idle floor is too loud\n";return 1;}
    for(int id=2;id<=21;++id){juce::String name;bool materialised=false;const auto difference=renderEditorPresetDifference(id,name,materialised);std::cout<<"Cartridge UI preset "<<name<<" mean dry difference: "<<difference<<"\n";if(!materialised||difference<.004f){std::cerr<<"Cartridge factory preset is inert through the real editor: "<<name<<"\n";return 1;}}
    const auto defaultImpulse=renderDefaultMaxImpulse();std::cout<<"Cartridge fresh-instance max impulse at 44.1k/512: "<<defaultImpulse<<"\n";if(defaultImpulse>.08f){std::cerr<<"Cartridge fresh instance creates click-sized discontinuities\n";return 1;}
    const auto transitionImpulse=renderPresetTransitionMaxImpulse();std::cout<<"Cartridge Arcade Cabinet transition max impulse: "<<transitionImpulse<<"\n";if(transitionImpulse>.08f){std::cerr<<"Cartridge preset transition creates a click-sized discontinuity\n";return 1;}
    std::cout<<"Cartridge adapter passed: canonical migration, conducted ROM/bank/chip events, telemetry, and safe output\n";
}
