export const PRESETS = {
  cleanCall: {
    name: "Clean Call",
    mode: "zoom",
    bandwidth: 0.75,
    codec: 0.15,
    dropouts: 0.05,
    jitter: 0.06,
    robot: 0.03,
    noise: 0.05,
  },
  discordCrunch: {
    name: "Discord Crunch",
    mode: "discord",
    bandwidth: 0.5,
    codec: 0.55,
    dropouts: 0.35,
    jitter: 0.22,
    robot: 0.18,
    noise: 0.12,
  },
  zoomRobot: {
    name: "Zoom Robot",
    mode: "zoom",
    bandwidth: 0.55,
    codec: 0.48,
    dropouts: 0.28,
    jitter: 0.25,
    robot: 0.45,
    noise: 0.1,
  },
  skype2008: {
    name: "Skype 2008",
    mode: "skype",
    bandwidth: 0.45,
    codec: 0.4,
    dropouts: 0.2,
    jitter: 0.18,
    robot: 0.12,
    noise: 0.09,
  },
  hotspotBad: {
    name: "Bad Hotspot",
    mode: "cell",
    bandwidth: 0.35,
    codec: 0.6,
    dropouts: 0.6,
    jitter: 0.35,
    robot: 0.25,
    noise: 0.16,
  },
  meltdown: {
    name: "Conference Meltdown",
    mode: "discord",
    bandwidth: 0.25,
    codec: 0.85,
    dropouts: 0.85,
    jitter: 0.75,
    robot: 0.65,
    noise: 0.25,
  },

  teamsClean: {
    name: "Teams Clean",
    mode: "zoom",
    bandwidth: 0.78,
    codec: 0.18,
    dropouts: 0.05,
    jitter: 0.05,
    robot: 0.02,
    noise: 0.04,
  },
  discordStudio: {
    name: "Discord Studio",
    mode: "discord",
    bandwidth: 0.7,
    codec: 0.22,
    dropouts: 0.06,
    jitter: 0.08,
    robot: 0.04,
    noise: 0.05,
  },
  zoomWifiSoft: {
    name: "Zoom (Soft WiFi)",
    mode: "zoom",
    bandwidth: 0.62,
    codec: 0.28,
    dropouts: 0.12,
    jitter: 0.14,
    robot: 0.06,
    noise: 0.06,
  },
  skypeFaint: {
    name: "Skype Faint",
    mode: "skype",
    bandwidth: 0.55,
    codec: 0.22,
    dropouts: 0.1,
    jitter: 0.12,
    robot: 0.05,
    noise: 0.06,
  },
  cellCallStable: {
    name: "Cell Call (Stable)",
    mode: "cell",
    bandwidth: 0.58,
    codec: 0.26,
    dropouts: 0.1,
    jitter: 0.1,
    robot: 0.04,
    noise: 0.06,
  },
};
