export const PRESETS = {
  cleanCall: {
    name: "Clean Call",
    mode: "zoom",
    bandwidth: 0.9,
    codec: 0.08,
    dropouts: 0.015,
    jitter: 0.015,
    robot: 0.01,
    noise: 0.025,
  },
  discordCrunch: {
    name: "Discord Packet Spiral",
    mode: "discord",
    bandwidth: 0.62,
    codec: 0.58,
    dropouts: 0.48,
    jitter: 0.42,
    robot: 0.56,
    noise: 0.06,
  },
  zoomRobot: {
    name: "Zoom Robot Voice",
    mode: "zoom",
    bandwidth: 0.7,
    codec: 0.42,
    dropouts: 0.38,
    jitter: 0.48,
    robot: 0.72,
    noise: 0.04,
  },
  skype2008: {
    name: "Skype 2008",
    mode: "skype",
    bandwidth: 0.45,
    codec: 0.46,
    dropouts: 0.24,
    jitter: 0.18,
    robot: 0.2,
    noise: 0.08,
  },
  hotspotBad: {
    name: "Bad Hotspot",
    mode: "cell",
    bandwidth: 0.35,
    codec: 0.64,
    dropouts: 0.7,
    jitter: 0.6,
    robot: 0.5,
    noise: 0.1,
  },
  meltdown: {
    name: "Conference Meltdown",
    mode: "discord",
    bandwidth: 0.25,
    codec: 0.86,
    dropouts: 0.9,
    jitter: 0.88,
    robot: 0.92,
    noise: 0.18,
  },

  teamsClean: {
    name: "Teams Clean",
    mode: "zoom",
    bandwidth: 0.78,
    codec: 0.14,
    dropouts: 0.02,
    jitter: 0.02,
    robot: 0.01,
    noise: 0.025,
  },
  discordStudio: {
    name: "Discord Studio",
    mode: "discord",
    bandwidth: 0.7,
    codec: 0.2,
    dropouts: 0.025,
    jitter: 0.04,
    robot: 0.025,
    noise: 0.03,
  },
  zoomWifiSoft: {
    name: "Zoom (Soft WiFi)",
    mode: "zoom",
    bandwidth: 0.62,
    codec: 0.3,
    dropouts: 0.18,
    jitter: 0.24,
    robot: 0.12,
    noise: 0.04,
  },
  skypeFaint: {
    name: "Skype Faint",
    mode: "skype",
    bandwidth: 0.55,
    codec: 0.22,
    dropouts: 0.1,
    jitter: 0.12,
    robot: 0.05,
    noise: 0.06,
  },
  cellCallStable: {
    name: "Cell Call (Stable)",
    mode: "cell",
    bandwidth: 0.58,
    codec: 0.26,
    dropouts: 0.1,
    jitter: 0.1,
    robot: 0.04,
    noise: 0.06,
  },
};
